### ISSUE TITLE
Question: (assert (and A B)) vs. (begin (assert A) (assert B))

### ISSUE THREAD

**Issue by penlu** [emina/rosette#102]
We seem to have run into some situation where (assert x) (assert y) (i.e. two sequential asserts) and (assert (and x y)) exhibit different behaviors. Some of our synthesis examples fail when the specification is expressed using one or the other.

We are wondering if we're using some construct incorrectly or perhaps our installs are bad. We're running these for identical results on (Ubuntu 16.04 + Racket 6.6 + `raco pkg install rosette`) and (Ubuntu 18.04 + Racket 6.12 + `raco pkg install rosette`).

Here are a couple files exhibiting this behavior:
* [example 1](https://gist.github.com/penlu/667a57edf3a932ac03a8698915545d2c)
* [example 2](https://gist.github.com/penlu/76d36656b3876cff1069bd3e8d82de3a)

Here are the assertions and output for each:
### assertions
```
(assert (bveq (unbox R0) (bv 3 32)))
(assert (bveq (unbox R0) (unbox R1)))
```
### output
```
(evaluate (unbox R0) model)
> (bv #x00000023 32)
(evaluate (unbox R1) model)
> (bv #x00000043 32)
```
These values don't seem to satisfy the second assertion. However if we write the assertions as follows, the output is fine.
```
(assert (and (bveq (unbox R0) (bv 3 32))
             (bveq (unbox R0) (unbox R1))))
```

### assertions
```
(assert (bveq (unbox R0) (bv 0 32)))
(assert (and (bveq (unbox R1) (bv 5 32))
             (bveq (unbox CPSR) (bv #x60000000 32))))
```
### output
```
(evaluate (unbox R0) model)
> (bv #x00000000 32)
(evaluate (unbox R1) model)
> (bv #x00000025 32)
(evaluate (unbox CPSR) model)
> (bv #x60000000 32)
```
The value in R1 doesn't seem to satisfy the second assertion, but changing the assertions to the following makes the output OK.
```
(assert (bveq (unbox R0) (bv 0 32)))
(assert (bveq (unbox R1) (bv 5 32)))
(assert (bveq (unbox CPSR) (bv #x60000000 32)))
```

**Comment by emina** [comment]
In both of these examples, the solver is accidentally choosing the right values for R0 and R1 when you use `and` versus a sequence of assertions.  To see what I mean, try commenting out [line 58](https://gist.github.com/penlu/667a57edf3a932ac03a8698915545d2c#file-example1-rkt-L58) in example 1, and you will see that the solver will once again choose values that happen to satisfy the second assertion as well.

The issue here (in both cases) is the use of the `bitvector->natural` operator. This operator returns a positive integer, and the precision of reasoning about integers during synthesis is controlled by the [current-bitwidth](https://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_rosette.html?q=current-bitwidth#%28def._%28%28lib._rosette%2Fquery%2Ffinitize..rkt%29._current-bitwidth%29%29) parameter.  This parameter is set to 5 bits by default, so this result is correct under that semantics. 

To get the right behavior, set `current-bitwidth` to 32 before calling `synthesize`:

```
(current-bitwidth 32)
; synthesis part
(define model ...)
```

Finally, neither example is  quantifying over symbolic values.  That is, `r0_init r1_init` in the call to `synthesize` are concrete bitvectors.  You can therefore rewrite these queries more simply as follows:

```
(define model
  (solve (begin (inst 2) ...)
```

**Comment by emina** [comment]
One more note.  Looking again at example1, you can get rid of the (expensive) integer->bitvector and bitvector->integer conversions entirely as follows:

```
#lang rosette

(require rosette/lib/synthax)

(provide (all-defined-out))

; register definitions
(define (regval32*)
  (define-symbolic* x (bitvector 32))
  x)

(define r0_init (bv 0 32))
(define r1_init (bv 1 32))

(define R0 (box r0_init))
(define R1 (box r1_init))
; unbox: return the content of box.
; set-box!: change the content of box

; instruction descriptions
(define (ADD_imm Rd Rn Imm) 
  (set-box! Rd (bvadd (unbox Rn) (zero-extend Imm (bitvector 32)))))

(define (ADD_reg Rd Rn Rm)
  (set-box! Rd (bvadd (unbox Rn) (unbox Rm))))

; generate the instruction list
; num indicates the number of the instruction list is (num + 1) 
(define-synthax (inst num)
  #:base (choose
          (ADD_imm (choose R0 R1) (choose R0 R1) (?? (bitvector 12)))
          (ADD_reg (choose R0 R1) (choose R0 R1) (choose R0 R1)))
  #:else (begin
           (choose
            (ADD_imm (choose R0 R1) (choose R0 R1) (?? (bitvector 12)))
            (ADD_reg (choose R0 R1) (choose R0 R1) (choose R0 R1)))
           (inst (- num 1))))

; synthesis part
(define model
  (solve
   (begin
     (inst 2)
     (assert (bveq (unbox R0) (bv 3 32)))
     (assert (bveq (unbox R0) (unbox R1))))))

(print-forms model)
(evaluate (unbox R0) model)
(evaluate (unbox R1) model)
; get the model result: (print-forms model)
; get the content of the registers: (evaluate (unbox R0) model)
```

In general, sticking to one theory (in this case bitvectors) will give you best performance.

Hope this helps!

**Comment by penlu** [comment]
Thanks very much! We also discovered `bvadd` once running with `(current-bitwidth #f)` hung the solver. In the future we will try to stick to single theories as you advise.
