### ISSUE TITLE
Question: create list/vector of concrete length

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#108]
Hello,

I am trying to move most of my work to use `rosette/safe`. However, I think this might turn out not to be possible.

For example, to create a vector of concrete length filled with symbols I do:
```
(define (build-symbols n)
    (build-vector n (lambda (i) (define-symbolic*  v integer?) v)))
```

No `list` or `vector` constructors like `build-vector` or `build-list` seem to be lifted. Do you have any suggestions on how to achieve this? Alternatively, I guess it would be possible to define a lifting using `define-lift`?

**Comment by emina** [comment]
Let me start with the short answer :)

If you are certain that your code will never call `build-vector` or `build-list` with a symbolic length, the simplest solution is to selectively require the Racket versions of these procedures and use them as-is.

For example:

```
#lang rosette/safe

(require (only-in racket build-vector))

(define (build-symbols n)
  (build-vector n (lambda (i) (define-symbolic*  v integer?) v)))

> (build-symbols 3)
(vector v$0 v$1 v$2)
```

Now, the long answer.  

The procedures such as `build-vector` aren't lifted because there is no way to do so that makes sense in general---the lifting needs to be application-specific for the following reason. While Rosette can be used to construct a vector or a list of unknown length, that unknown length must always be bounded by a concrete upper bound. So, we can construct a list of "length to up k" where k is concrete, but we cannot construct a list of length k, where k is unknown. The former use case would be implemented like this:

```
(define k 5) ; upper bound
(define-symbolic* v integer? [k]) ; list of k integers
(define-symbolic n integer?) ; unknown length
(define vn (take v n)) ; list of up to k integers

> (length vn)
(ite* (⊢ (= 0 n) 0) (⊢ (= 1 n) 1) (⊢ (= 2 n) 2) (⊢ (= 3 n) 3) (⊢ (= 4 n) 4) (⊢ (= 5 n) 5))
```

Because we cannot construct a vector or a list of unknown length, there is no way to provide a sensible generic implementation for `build-vector` where the input `n` is symbolic.  So, if you needed to handle this particular use case, you'd want to control the default upper bound on the length of the constructed vector.  One way to do so would be as follows:

```
(require
  (only-in racket
           [integer? concrete-integer?]
           [build-list concrete-build-list]))

(define default-k 3)

(define (build-vector n proc)
  (apply
   vector
   (if (concrete-integer? n)
       (concrete-build-list n proc)
       (take (concrete-build-list default-k proc) n))))

> (build-vector 4 identity)
'#(0 1 2 3)
> (define-symbolic* n integer?)
> (build-vector n identity)
{[(= 0 n$0) #()] [(= 1 n$0) #(0)] [(= 2 n$0) #(0 1)] [(= 3 n$0) #(0 1 2)]}
> (asserts) ; n is implicitly bound by k
(list (&& (<= 0 n$0) (< n$0 4)))
```
