### ISSUE TITLE
Broken error message for assoc

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#111]
Apologies for the several edits - kept pressing enter by mistake.

When mistaking the order in which to write `assoc` arguments I get in racket:
```
> (assoc '() 0)
; assoc: not a proper list: 0 [,bt for context]
```

but in rosette:
```
> (assoc '() 0)
; findf: contract violation
;   expected: #<procedure:list?>
;   given: 0
; [,bt for context]
```

took me a while to figure out what was going on because I knew I had no `findf` in my codebase.

**Comment by emina** [comment]
Thanks for the note.

The message is coming from Rosette's internal (lifted) implementation of `assoc`, since that's where the code is failing.  The underlying cause is the same as in Racket: wrong types / swapped arguments. Rosette's implementation of `assoc` is different (it uses the lifted `findf`), so the error manifests in a different location, with a different error message. In general, it would be too hard to ensure one-to-one mapping from Rosette error messages to Racket error messages.

**Comment by pmatos** [comment]
Agree that error messages don't need to be the same but rosette should still complain about `assoc`, not an internal function that the user doesn't know about.

**Comment by emina** [comment]
When a function (in this case `assoc`) is implemented in terms of other functions (in the case `findf`), and the failure happens in the callee, it's not unusual for the error message to come from the callee :) 

In some cases, it's possible for the caller to repeat the checks done in the callee (here, the type checks) to ensure a nice error message.  In other cases, those checks are too expensive to repeat.  That's the case here: repeating the type checks can be quite expensive if the inputs are symbolic so it's not done.
