### ISSUE TITLE
read-solution: unrecognized solver output: #<eof>

### ISSUE THREAD

**Issue by alexlisitsa** [emina/rosette#117]
I have installed Rosetta both on WIndows 7 and Linux (not Unix-type installation) system. In both cases I hit the same issue when tried some tutorial examples for verification: 

>(define (poly x)
> (+ (* x x x x) (* 6 x x x) (* 11 x x) (* 6 x)))
> 
>(define (factored x)
> (* x (+ x 1) (+ x 2) (+ x 2)))
> 
>(define (same p f x)
> (assert (= (p x) (f x))))
>
>Welcome to DrRacket, version 7.2 [3m].
>Language: rosette/safe, with debugging; memory limit: 128 MB.
> (same poly factored 0)
> (define-symbolic i integer?)
> (define cex (verify (same poly factored i)))
. . racket/collects/racket/private/kw.rkt:1325:47: read-solution: unrecognized solver output: #<eof>
> 
Any hint how to fix it? 
Thank you.

**Comment by emina** [comment]
This error usually happens when Rosette is unable to call the underlying solver through a pipe.

So, it appears to be an installation / OS issue.

You can try installing everything from source, which will hopefully fix the issue.

To install Rosette from source, follow the instructions in the README.

For Z3, download the source for the version you'd like to use, compiling, and place the resulting binary (named just `z3`) into `rosette/bin`.

**Comment by Hoernchen** [comment]
In case anyone hits this with bitwuzla: the bitwuzla version might be too old, and requires exporting BTORINCREMENTAL=1 to support incremental usage, which makes it work.
