### ISSUE TITLE
Report unbound id

### ISSUE THREAD

**Issue by sorawee** [emina/rosette#119]
(Observed by @JacobVanGeffen) 

```
(synthesize 
  #:forall null
  #:guarantee (assert foobar))
```
where `foobar` is unbound results in `(unsat)`. This should result in an unbound id error instead.

**Comment by emina** [comment]
This produces an unbound ID error when executed as a definition.

When executed from the REPL, this produces 'unsat because the REPL behaves differently: it throws an exception that Rosette can catch.  Every such exception is treated as an assertion failure.  

Since the semantics of `synthesize` is to return `(unsat)` if there is no way to fill the holes to make all the assertions pass for inputs, this is the expected behavior.

The same happens for `verify` in the definitions versus the REPL:

```
> (verify (assert foobar))
(model)
```
