### ISSUE TITLE
define-synthax does not create unique holes in bvlang

### ISSUE THREAD

**Issue by rachitnigam** [emina/rosette#123]
I was playing with the example code here: https://courses.cs.washington.edu/courses/cse507/19wi/doc/bvlang.rkt

I added the following code:
```
(define-synthax gate??
  ([(_) (choose bvneg bvsge bvxor bvand)]))
```

and modified `bvmax1` to be:
```
(def bvmax1
  ([0 r0] [1 r1]) 
  (2 bvsge 0 1)
  (3 (gate??) (??))
  (4 (gate??) 0 (??))
  (5 bvand 3 4)
  (6 bvxor (??) 5))
```

from the original definition of:
```
(def bvmax1
  ([0 r0] [1 r1]) 
  (2 bvsge 0 1)
  (3 bvneg (??))
  (4 bvxor 0 (??))
  (5 bvand 3 4)
  (6 bvxor (??) 5))
```

I expected the `synthesize` query to fill in the `gate??` with two bit vector commands but it returns `unsat`. I also tried manually inlining the `choose` query but that doesn't seem to help.

If I move the `gate??` holes to be in both the occurrences of `bvxor`, the query succeeds: 
```
(def bvmax1
  ([0 r0] [1 r1]) 
  (2 bvsge 0 1)
  (3 bvneg (??))
  (4 (gate??) 0 (??))
  (5 bvand 3 4)
  (6 (gate??) (??) 5))
```

This seems to imply to me that the `gate??` creates a single named hole and uses it for all occurrences of `gate??`. Is there a way to fix this issue? I suspect the `def/dbg` macro is causing some issues with locations and how `define-synthax` creates unique names for complex holes

---

At a high level, I want to give the synthesizer a specification and ask it to produce of program of size `n`. Any suggestions on how to accomplish this? I noticed that the `bv` language in the sdsl uses `structs` to generate programs of some size but I'm not entirely sure how it works. A brief explanation would be helpful.

**Comment by jamesbornholt** [comment]
The problem is that this example quotes instructions and then passes them to `eval`. `define-synthax` depends on syntax location information to create unique holes, but quoting loses the syntax information, so the two `(gate??)` calls end up having the same (empty) location and thus share the same hole.

To answer your high-level question, I don't think extending this example code is likely to get you the results you're looking for. A better approach will be to build your own DSL syntax and semantics. Here's [an example](https://homes.cs.washington.edu/~bornholt/post/building-synthesizer.html) of what that looks like for AST-shaped DSLs, or [another example](https://gist.github.com/jamesbornholt/0ecbe007dd067640f73fc2c8094d0098) for a register machine similar to the BV language.
