### ISSUE TITLE
Getting solver times from queries

### ISSUE THREAD

**Issue by rachitnigam** [emina/rosette#124]
I'm trying to extract the time that Rosette spends in the SMT solver for benchmarking some of my code.

I assume there is a simple way of creating a new `solver` instance using a base solver but it seems that `symprofile` already records a bunch of useful data that can't be extracted from just overriding the solver (merge counts, unions, etc).

Would it be possible to expose `current-reporter` from `core/reporter.rkt`? 

I was able to quickly expose it locally by adding a line to `base.rkt` and overriding the parameter with a reporter that only listens for `'solver-start` and `'solver-finish`. I assume other people might find it useful to get these metrics from rosette for benchmarking purposes.

Proposed changes here: https://github.com/rachitnigam/rosette/commit/88d7af4795172de946c5aed61b9fc78942c9f644 (happy to add documentation and open a PR if this seems useful)

**Comment by emina** [comment]
There is no need to expose `current-reporter` since you can require directly into your Rosette program, e.g.:

```
#lang rosette

(require rosette/base/core/reporter)

(current-reporter)
```

**Comment by jamesbornholt** [comment]
You could also just use Racket’s `time` (and its cousin `time-apply`), which report both the CPU and wall clock time to evaluate an expression. Time spent in solving counts as wall clock time but not CPU time, since it’s external to Racket, so the difference between the two is an estimate of solving time. (This is how I usually measure solving time).
