### ISSUE TITLE
Adding new solvable types

### ISSUE THREAD

**Issue by tchajed** [emina/rosette#125]
Is it possible to extend the set of solvable types?

Our use cases are for `positive?` and for our structs (which are composed of solvable types). We can work around this by just wrapping `define-symbolic`, but it would be cool to just hook into Rosette directly.

**Comment by emina** [comment]
A solvable type is a datatype that an SMT solver can reason about directly and effectively (see [here](https://docs.racket-lang.org/rosette-guide/ch_built-in-datatypes.html#%28tech._solvable._type%29)). Rosette reduces the program semantics to a formula expressed over symbolic constants of those types, and this formula is handed off to the solver as-is.  So, Racket types such as `positive?` cannot be solvable since there is no corresponding type in SMTLib.

The usual solution is to define a macro or a procedure that encodes instances of the datatype you want  in terms of solvable types, constraining them with assertions to enforce additional properties. 

Here is an example solution that defines its own notion of a "typed struct" and uses that to create fresh symbolic instances of any datatype constructed using `struct/typed`.  

```
#lang rosette

(define-values (prop:struct/typed struct/typed? struct/typed-ref)
  (make-struct-type-property 'struct/typed))

(define-syntax (struct/typed stx)
  (syntax-case stx ()
    [(_ id ([field type] ...) rest ...)
     (quasisyntax/loc stx
       (struct id (field ...)
         rest ...
         #:property prop:struct/typed
         (lambda ()
           (define-symbolic* field type) ...
           (id field ...))))]))
            
; Takes as input a struct/typed? value and returns a fresh symbolic
; instance of the given struct type.
(define (make-symbolic-struct type)
  (let ([symbolic-constructor (struct/typed-ref type)])
    (symbolic-constructor)))
  

(struct/typed foo ([x integer?] [y boolean?]) #:transparent)

> (make-symbolic-struct struct:foo)
(foo x$0 y$0)
> (make-symbolic-struct struct:foo)
(foo x$1 y$1)
```
