### ISSUE TITLE
Symbolic unions pretty-print poorly

### ISSUE THREAD

**Issue by florence** [emina/rosette#129]
For example I have a list containing exactly 1 symbolic union, which pretty-prints as:

```
'({[(&& (! pos-A$0) (|| pos-A$0 (&& neg-A$1 (! pos-A$0)))) ((O ⊥))] [(! (&& (! pos-A$0) (|| pos-A$0 (&& neg-A$1 (! pos-A$0))))) ({2168448574984830752:2}
                                                                                                                                 (O
                                                                                                                                  ⊥))]})
```

if I copy/paste this an re-`pretty-print` it i get:

```
'((((&& (! pos-A$0) (|| pos-A$0 (&& neg-A$1 (! pos-A$0)))) ((O ⊥)))
   ((! (&& (! pos-A$0) (|| pos-A$0 (&& neg-A$1 (! pos-A$0)))))
    ((2168448574984830752:2) (O ⊥)))))
```

Which is much easier to read indentation wise, but looses a the `{` and `[`'s which make unions much easier to read.

Better pretty printing would make my models much easier to debug!

**Comment by emina** [comment]
We recommend writing custom pretty-printers for debugging, since different applications have different needs regarding indentation and the level of detail to display in unions (e.g., nothing, just guards, just values, both, etc.).  You can do this easily via [symbolic reflection](https://docs.racket-lang.org/rosette-guide/sec_value-reflection.html).
