### ISSUE TITLE
Bit vector rotates?

### ISSUE THREAD

**Issue by whitequark** [emina/rosette#136]
It would be very nice to have bit vector rotate functions in the Rosette standard library. I tried to add them myself but the bit vector operations in bitvector.rkt seem to be very involved for reasons I don't understand. Here's my implementation:
```racket
(define (rotate-right i x)
  (define s (bitvector-size (type-of x)))
  (concat (extract (- i 1) 0 x) (extract (- s 1) i x)))
(define (rotate-left i x)
  (define s (bitvector-size (type-of x)))
  (concat (extract (- s i 1) 0 x) (extract (- s 1) (- s i) x)))
```

**Comment by emina** [comment]
This implementation makes assumptions that aren't true for general Rosette code.  For example, here is a valid attempt to use `rotate-right` that fails:

```
> (define-symbolic b boolean?)
> (rotate-right 1 (if b (bv 3 32) (bv 4 64)))
. . bitvector-size: contract violation
  expected: bitvector?
  given: any/c
```

This fails because `rotate-right` is using `bitvector-size` in an unsafe way. Specifically, `bitvector-size` assumes that its input is not a symbolic union. So, Rosette does a lot of work to establish the preconditions assumed by its internal helper procedures such as `bitvector-size` (which aren't exported for this reason---establishing the preconditions is non-trivial).

**Comment by emina** [comment]
To clarify:  `bitvector-size` is export but not document because we don't necessarily recommend using it :)

**Comment by whitequark** [comment]
Right--that my implementation had issues I do not understand is exactly why I think that having one in the standard library would have been useful.
