### ISSUE TITLE
Adding variants to choose* causes synthesize to start returning unsat

### ISSUE THREAD

**Issue by whitequark** [emina/rosette#137]
The following program, when run as-is, correctly synthesizes an instruction sequence. However, if the lines marked as `XXX` are uncommented, it fails to do so as `synthesize` returns `(unsat)`.

<details>

```racket
#lang rosette/safe

(require rosette/lib/angelic
         rosette/lib/match)
(current-bitwidth #f)

; bit operations
(define (replace-bit i x y)
  (define m (bvshl (bv 1 (type-of x)) (integer->bitvector i (type-of x))))
  (cond
    [(bveq y (bv 0 1)) (bvand x (bvnot m))]
    [(bveq y (bv 1 1)) (bvor x m)]
    [else (assert #f)]))
  
; CPU state
(struct state (A C Rn) #:mutable #:transparent)

(define (state-Rn-ref S n)
  (vector-ref (state-Rn S) n))
(define (state-Rn-set! S n v)
  (vector-set! (state-Rn S) n v))

(define-symbolic A R0 R1 R2 R3 R4 R5 R6 R7 (bitvector 8))
(define-symbolic C (bitvector 1))
(define (make-state)
  (state A C (vector R0 R1 R2 R3 R4 R5 R6 R7)))

; instructions
(struct MOV-A-Rn (n) #:transparent)
(struct MOV-Rn-A (n) #:transparent)
(struct XRL-A-Rn (n) #:transparent)
(struct XCH-A-Rn (n) #:transparent)
(struct CLR-C () #:transparent)
(struct MOV-C-An (n) #:transparent) 
(struct MOV-An-C (n) #:transparent) 
(struct RLC-A () #:transparent)
(struct RRC-A () #:transparent)
(struct RL-A () #:transparent)
(struct RR-A () #:transparent)

(define (print-insn insn)
  (match insn
    [(MOV-A-Rn n) (printf "MOV A, R~s~n" n)]
    [(MOV-Rn-A n) (printf "MOV R~s, A~n" n)]
    [(XRL-A-Rn n) (printf "XRL A, R~s~n" n)]
    [(XCH-A-Rn n) (printf "XCH A, R~s~n" n)]
    [(CLR-C)      (printf "CLR C~n")]
    [(MOV-C-An n) (printf "MOV C, ACC.~s~n" n)]
    [(MOV-An-C n) (printf "MOV ACC.~s, C~n" n)]
    [(RLC-A)      (printf "RLC A~n")]
    [(RRC-A)      (printf "RRC A~n")]
    [(RL-A)       (printf "RL A~n")]
    [(RR-A)       (printf "RR A~n")]))

; sketches
(define (??insn)
  (let ([n (choose* 0 1 2 3 4 5 6 7)])
    (choose* (MOV-A-Rn n)
             (MOV-Rn-A n)
             (XRL-A-Rn n)
             (XCH-A-Rn n)
             (CLR-C)
             (MOV-C-An n) ; YYY
             (MOV-An-C n) ; YYY
             ;(RLC-A) ; XXX
             ;(RRC-A) ; XXX
             (RL-A)
             (RR-A)
             )))

(define (??prog fuel)
  (if (= fuel 0) null
      (cons (??insn) (??prog (- fuel 1)))))

; symbolic interpreter
(define (run-insn S insn)
  (match insn
    [(MOV-A-Rn n)
     (set-state-A! S (state-Rn-ref S n))]
    [(MOV-Rn-A n)
     (state-Rn-set! S n (state-A S))]
    [(XRL-A-Rn n)
     (set-state-A! S (bvxor (state-A S) (state-Rn-ref S n)))]
    [(XCH-A-Rn n)
     (let ([A (state-A S)] [Rn (state-Rn-ref S n)])
       (set-state-A! S Rn) (state-Rn-set! S n A))]
    [(CLR-C)
     (set-state-C! S (bv 0 1))]
    [(MOV-C-An n)
     (set-state-C! S (extract n n (state-A S)))]
    [(MOV-An-C n)
     (set-state-A! S (replace-bit n (state-A S) (state-C S)))]
    [(RLC-A)
     (let ([A (state-A S)] [C (state-C S)])
       (set-state-A! S (concat (extract 6 0 A) C))
       (set-state-C! S (extract 7 7 A)))]
    [(RRC-A)
     (let ([A (state-A S)] [C (state-C S)])
       (set-state-A! S (concat C (extract 7 1 A)))
       (set-state-C! S (extract 0 0 A)))]
    [(RL-A)
     (let ([A (state-A S)])
       (set-state-A! S (concat (extract 6 0 A) (extract 7 7 A))))]
    [(RR-A)
     (let ([A (state-A S)])
       (set-state-A! S (concat (extract 0 0 A) (extract 7 1 A))))]
    ))

; program synthesizer
(define (synthesize-prog sketch asserts)
  (define S  (make-state))
  (define S* (make-state))
  (define solution
    (synthesize
     #:forall S
     #:guarantee
     (begin
       (for-each (curry run-insn S*) sketch)
       (asserts S S*))))
  (if (unsat? solution) #f
      (begin
        (for-each print-insn (evaluate sketch solution))
        #t)))

; examples
(synthesize-prog
 (??prog 4)
 (lambda (S S*)
   (assert (bveq
            (concat (extract 7 1 (state-Rn-ref S 0)) (bv 0 1))
            (state-Rn-ref S* 0)))))
```
</details>

How is this possible? My understanding is that adding a new variant to `(choose* ...)`, by itself, can never cause a previously valid solution to not be found, because even if choosing the new path always causes an error, the solver should simply never choose that path.

Moveover, the code interpreting `RLC-A` and `RRC-A` *seems* correct: if the lines marked as `YYY` are commented, the lines marked as `XXX` are uncommented, and `(??prog 4)` is changed to `(??prog 5)`, then it correctly synthesizes a different instruction sequence.

**Comment by emina** [comment]
I'm not sure what is the intended behavior here, so my solution may not be the right one, but the error still seems to be violations of implicit assumptions. These implicit violations are resulting in unexpected behavior.


To see the problem, run the following version of your code with `ZZZ` commented out (things work) and not (things don't work).   

<details>
#lang rosette/safe

(require rosette/lib/angelic
         rosette/lib/match)
(current-bitwidth #f)

; bit operations
(define (replace-bit i x y)
  (printf "type-of x: ~a\n" (type-of x))
  (define m (bvshl (bv 1 (type-of x)) (integer->bitvector i (type-of x))))
  (cond
    [(bveq y (bv 0 1)) (bvand x (bvnot m))]
    [(bveq y (bv 1 1)) (bvor x m)]
    [else (assert #f)]))
  
; CPU state
(struct state (A C Rn) #:mutable #:transparent)

(define (state-Rn-ref S n)
  (vector-ref (state-Rn S) n))
(define (state-Rn-set! S n v)
  (vector-set! (state-Rn S) n v))

(define-symbolic A R0 R1 R2 R3 R4 R5 R6 R7 (bitvector 8))
(define-symbolic C (bitvector 1))
(define (make-state)
  (state A C (vector R0 R1 R2 R3 R4 R5 R6 R7)))

; instructions
(struct MOV-A-Rn (n) #:transparent)
(struct MOV-Rn-A (n) #:transparent)
(struct XRL-A-Rn (n) #:transparent)
(struct XCH-A-Rn (n) #:transparent)
(struct CLR-C () #:transparent)
(struct MOV-C-An (n) #:transparent) 
(struct MOV-An-C (n) #:transparent) 
(struct RLC-A () #:transparent)
(struct RRC-A () #:transparent)
(struct RL-A () #:transparent)
(struct RR-A () #:transparent)

(define (print-insn insn)
  (match insn
    [(MOV-A-Rn n) (printf "MOV A, R~s~n" n)]
    [(MOV-Rn-A n) (printf "MOV R~s, A~n" n)]
    [(XRL-A-Rn n) (printf "XRL A, R~s~n" n)]
    [(XCH-A-Rn n) (printf "XCH A, R~s~n" n)]
    [(CLR-C)      (printf "CLR C~n")]
    [(MOV-C-An n) (printf "MOV C, ACC.~s~n" n)]
    [(MOV-An-C n) (printf "MOV ACC.~s, C~n" n)]
    [(RLC-A)      (printf "RLC A~n")]
    [(RRC-A)      (printf "RRC A~n")]
    [(RL-A)       (printf "RL A~n")]
    [(RR-A)       (printf "RR A~n")]))

; sketches
(define (??insn)
  (let ([n (choose* 0 1 2 3 4 5 6 7)])
    (choose* (MOV-A-Rn n)
             (MOV-Rn-A n)
             (XRL-A-Rn n)
             (XCH-A-Rn n)
             (CLR-C)
             (MOV-C-An n) ; YYY
             (MOV-An-C n) ; YYY
             (RLC-A) ; XXX
             (RRC-A) ; XXX
             (RL-A)
             (RR-A)
             )))

(define (??prog fuel)
  (if (= fuel 0) null
      (cons (??insn) (??prog (- fuel 1)))))

; symbolic interpreter
(define (run-insn S insn)
  (match insn
    [(MOV-A-Rn n)
     (set-state-A! S (state-Rn-ref S n))]
    [(MOV-Rn-A n)
     (state-Rn-set! S n (state-A S))]
    [(XRL-A-Rn n)
     (set-state-A! S (bvxor (state-A S) (state-Rn-ref S n)))]
    [(XCH-A-Rn n)
     (let ([A (state-A S)] [Rn (state-Rn-ref S n)])
       (set-state-A! S Rn) (state-Rn-set! S n A))]
    [(CLR-C)
     (set-state-C! S (bv 0 1))]
    [(MOV-C-An n)
     (set-state-C! S (extract n n (state-A S)))]
    [(MOV-An-C n)
     (set-state-A! S (replace-bit n (state-A S) (state-C S)))]
    [(RLC-A)
     (let ([A (state-A S)] [C (state-C S)])
       ;(set-state-A! S (concat (extract 6 0 A) C)) ; ZZZ
       (set-state-C! S (extract 7 7 A)))]
    [(RRC-A)
     (let ([A (state-A S)] [C (state-C S)])
       ;(set-state-A! S (concat C (extract 7 1 A))) ; ZZZ
       (set-state-C! S (extract 0 0 A)))]
    [(RL-A)
     (let ([A (state-A S)])
       (set-state-A! S (concat (extract 6 0 A) (extract 7 7 A))))]
    [(RR-A)
     (let ([A (state-A S)])
       (set-state-A! S (concat (extract 0 0 A) (extract 7 1 A))))]
    ))

; program synthesizer
(define (synthesize-prog sketch asserts)
  (define S  (make-state))
  (define S* (make-state))
  (define solution
    (synthesize
     #:forall S
     #:guarantee
     (begin
       (for-each (curry run-insn S*) sketch)
       (asserts S S*))))
  (if (unsat? solution) #f
      (begin
        (for-each print-insn (evaluate sketch solution))
        #t)))

; examples
(synthesize-prog
 (??prog 4)
 (lambda (S S*)
   (assert (bveq
            (concat (extract 7 1 (state-Rn-ref S 0)) (bv 0 1))
            (state-Rn-ref S* 0)))))

; Output without ZZZ:
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: (bitvector 8)
CLR C
XCH A, R0
MOV ACC.0, C
MOV R0, A
#t

; Output with ZZZ
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: any/c
type-of x: any/c
#f

</details>

If we change `replace-bit` as follows, then everything works as expected: 

```
(define (replace-bit i x y)
  (printf "type-of x: ~a\n" (type-of x))
  (define m (bvshl (bv 1 (bitvector 8)) (integer->bitvector i (bitvector 8))))
  (cond
    [(bveq y (bv 0 1)) (bvand x (bvnot m))]
    [(bveq y (bv 1 1)) (bvor x m)]
    [else (assert #f)]))

; Output with ZZZ enabled:
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: any/c
type-of x: any/c
XCH A, R0
CLR C
MOV ACC.0, C
XCH A, R0

; Output with ZZZ disabled:
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: (bitvector 8)
type-of x: (bitvector 8)
CLR C
XCH A, R0
MOV ACC.0, C
MOV R0, A
```

Note that problem here is that the semantics of `RLC-A` and `RRC-A` introduces a "type error" into the state from which the interpreter cannot recover later on, because `type-of` will return `any/c` that causes an internal error in `bv` and `integer->bitvector` that prevents `(MOV-An-C 0)` from being in the 3rd or 4th slot. 

One way to let the solver avoid this error in the code with `ZZZ` enabled, and without changing `replace-bit`, is to introduce more freedom into the sketch:

```
; everything is the same as the example code except the following:
(synthesize-prog
 (??prog 5)
 (lambda (S S*)
   (assert (bveq
            (concat (extract 7 1 (state-Rn-ref S 0)) (bv 0 1))
            (state-Rn-ref S* 0)))))

; now, the solver finds a solution that puts (MOV-A-Rn 0) into the first slot
type-of x: (bitvector 8)
type-of x: any/c
type-of x: any/c
type-of x: any/c
MOV A, R0
RR A
CLR C
RLC A
XCH A, R0
```

**Comment by whitequark** [comment]
Thank you for the explanation. I understand that the practical implication here is that I should just never create bit vectors of type that may depend in any way on a symbolic union, and rather explicitly pass bit vector width to functions like `replace-bit` or `rotate-right`.

However, I'd like to understand *why* is that the case. As far as I can tell, the type of `(state-C S)` is always `(bitvector 1)`, and the type of `(state-A S)` is always `(bitvector 8)`, so it follows that the type of `(concat (extract 6 0 A) C))` is always `(bitvector 8)` as well. Where does the type error come from? Or equivalently, I can't see any branch decisions that would lead to anything other than a `(bitvector 8)` being stored to `(state-A S)`; could you point me to a trace that does?

> One way to let the solver avoid this error in the code with `ZZZ` enabled, and without changing `replace-bit`, is to introduce more freedom into the sketch:

Indeed I have discovered this, but the entire point of using Rosette in this case is to find an optimal instruction sequence according to a model I provide, so it's unfortunately not a viable solution.

**Comment by emina** [comment]
Ah, so, the type issues happen even in the absence of these two instructions.  It's just that in their absence, the `x` argument to `replace-bit` always has the right type, because Rosette's rewrite rules kick in and simplify away some of these issues.  (That is, they are able to prove some equivalences without calling out to Z3.)

The main issue is with `C`, which is not always `(bitvector 1)`.  To see that, add the following `printf` expression to the beginning of `run-insn`: 

```(printf "S-C: ~a, S-A: ~a\n" (type-of (state-C S)) (type-of (state-A S)))```

The problematic instruction is this one `(MOV-C-An n)`: 

```
> (define S (make-state))
> (define n (choose* 0 1 2 3 4 5 6 7))
> (run-insn S (MOV-C-An n))
> (type-of (state-C S))
any/c
```

Basically, Rosette [lacks a rewrite rule](https://github.com/emina/rosette/blob/master/rosette/base/core/bitvector.rkt#L579) that lets it determine that `(extract n n (state-A S)))` is a 1-bit value for every `n`.  What it does instead is conservatively consider the cross-product of all possible values for each occurrence of `n` in this expression, resulting in a union, because its rewrite rules cannot tell that certain combinations are guaranteed to be false,  such the first occurrence of `n` being a different concrete integer than than the second occurrence of `n`. 

```
> (map type-of (union-values (state-C S)))
'((bitvector 8) (bitvector 7) (bitvector 6) (bitvector 5) (bitvector 4) (bitvector 3) (bitvector 2) (bitvector 1))
```

To help Rosette prune some of these infeasible paths, we can replace `(set-state-C! S (extract n n (state-A S)))` with `(for/all ([n n #:exhaustive]) (set-state-C! S (extract n n (state-A S))))`. 

This will have the desired effect, and `replace-bit` can remain as-is (i.e., using `type-of`).

**Comment by whitequark** [comment]
Thank you for the explanation. I did notice that adding `MOV-C-An` has caused various issues, but did not understand the cause. Another effect of your suggestion is that performance is higher by 2-3 orders of magnitude, which I can also see in the profiler as a corresponding reduction in term count and union size.

It looks like a good way to catch these issues is to profile the program regularly and investigate any addition that causes an unexpected increase in term count.

**Comment by emina** [comment]
Yes, absolutely.  

For this particular case, I've just added a rewrite rule for `extract` that should now catch this.  So the unmodified initial example should work as-is! 

In general, we try to keep the number of the rewrite rules small (it's a tradeoff) but this one seems generally useful, and it adds very little overhead.

Thanks for catching it!

**Comment by whitequark** [comment]
Thank you for the fix! I really enjoy using Rosette so far, even if sometimes debugging can be a bit frustrating, and I very much appreciate your quick and in-depth responses here.

**Comment by emina** [comment]
Happy to help!  The more people use Rosette, the more issues get solved and the better it gets :)
