### ISSUE TITLE
Struct with lots of fields: slow compilation (performance bug?)

### ISSUE THREAD

**Issue by anishathalye** [emina/rosette#147]
I'm working on a project that involves auto-generating Rosette code, and part of it involves emitting `struct`s with many fields (on the order of hundreds or thousands). I found that compilation time (`raco make` time) is superlinear in the number of field structs.

I tried a simple experiment, compiling this program for varying values of N:

```racket
#lang rosette/safe
(struct foo (foo-1 foo-2 ... foo-N))
```

Here are the results:

![rosette](https://user-images.githubusercontent.com/3526486/76145511-ff4ed880-6057-11ea-8cd6-5d37027ec0f1.png)

It looks like `struct` from `#lang racket` has a superlinear behavior too, albeit with a smaller constant (this is the same data as above, but showing only `#lang racket` so it's easier to see):

![racket](https://user-images.githubusercontent.com/3526486/76145523-1392d580-6058-11ea-94ed-ad621951ed19.png)

If this is outside the intended use case of Rosette, feel free to close this issue. But I thought it would be good to check in, in case this is considered to be a performance bug and may be fixed. (Otherwise, I will find a workaround for my unusual use case.)

In case it's relevant, here's info about the machine on which I ran the experiment described above:

```console
$ uname -srvo
Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) GNU/Linux
$ racket --version
Welcome to Racket v7.4.
$ raco pkg show | grep rosette
 rosette  efe22c924b93e11ff60...  catalog...mina/rosette
```

I could reproduce this on my macOS machine as well (macOS 10.14.6, Racket v7.3, Rosette efe22c924b93e11ff60...).

In case it's helpful, here is the benchmark code:

```python
import subprocess
import time
for lang in ['racket', 'rosette/safe']:
    print(lang)
    for mem in range(50, 1500, 25):
        with open('test.rkt', 'w') as f:
            f.write('#lang {}\n'.format(lang))
            f.write('(struct foo ({}))\n'.format(' '.join('foo-{}'.format(i) for i in range(mem))))
        start = time.time()
        subprocess.check_call(['raco', 'make', 'test.rkt'])
        end = time.time()
        print('{} {}'.format(mem, end-start))
```

**Comment by emina** [comment]
Thank you for the thorough issue report!

Rosette does indeed add a non-trivial overhead to Racket structs.  Essentially, it has to wrap every single field accessor and mutator procedure generated by Racket, in order to properly handle the application of these functions to symbolic `struct` values.  I just took a brief look at this code and I don't see any obvious issues with the way this is done---though that doesn't mean it can't be made faster.  I'll take a more thorough look in the next few days.

That said, this is an unusual case for Rosette and I suspect for Racket as well, given your finding that the compilation time increases super linearly with the number of struct fields in both cases. So, I would advise changing to a different representation.  

Based your question,  I'm guessing that you are trying to generate a shallow embedding of some problem in Rosette from an external script.  This can work well, but in general, we have found that we get better performance and more flexibility with a deep embedding.

I'd be happy to chat about alternative ways to solve your problem.  Feel free to ping me via email.
