### ISSUE TITLE
Matching of nested lists doesn't seem to work

### ISSUE THREAD

**Issue by kenmcmil** [emina/rosette#175]
Here's an example:

```
#lang rosette
(define-symbolic c integer?)
(match (if (eq? c 0) '((x)) '((y))) ['((x)) 2] ['((y)) 3])
```

This should yield `(ite c 2 3)` but instead gives:

```
match: no matching clause for '(({[(= 0 c) x] [(! (= 0 c)) y]}))
```

**Comment by kenmcmil** [comment]
Sorry, it doesn't depend on nesting. This also fails:

```
#lang rosette
(define-symbolic c integer?)
(match (if (eq? c 0) '(x) '(y)) ['(x) 2] ['(y) 3])
```

Gives this error:

```
match: no matching clause for '({[(= 0 c) x] [(! (= 0 c)) y]})
```

It seems like Rosette is pushing the conditional inside the lists and then failing to match.

This situation occurs in a small-step interpreter evaluating a conditional.

**Comment by kenmcmil** [comment]
In fact, it doesn't depend on matching a list. Matching anything with the `{[c1 v1] ...[cn vn]}` notation seems to fail.

```
#lang rosette
(define-symbolic c integer?)
(match (car (if (eq? c 0) '(x) '(y))) ['x 2] ['y 3])
```

gives:

```
match: no matching clause for {[(= 0 c) x] [(! (= 0 c)) y]}
```

Anyway, I see that "match" is not supported in rosette/safe. Sorry if this is a known bug.

**Comment by emina** [comment]
You're right, `match` isn't lifted by Rosette, which is why these examples aren't working as expected. 

Racket's `match` is complex and would require a lot of effort to lift, so we've chosen to omit it for now.

But we've recently implemented a limited version of matching that covers some typical use cases (such as writing interpreters): 

https://docs.racket-lang.org/rosette-guide/sec_utility-libs.html#%28part._.Value_.Destructuring_.Library%29

Hope that helps!

**Comment by kenmcmil** [comment]
That's great, thanks!
