### ISSUE TITLE
(bitvector 1) vs boolean 

### ISSUE THREAD

**Issue by threonorm** [emina/rosette#182]
There are nice simplifications when working with booleans, which disappear when working with bitvector 1.

For example:
```
    (define-symbolic b boolean?)
    (define valid (box b))
    (if (not (unbox valid))
          (set-box! valid #t)
          (void))
    (if (not (unbox valid))
          (set-box! valid #t)
          (void))
    
    ; Rosette manages to greatly simplifies, valid is #&#t
```
Though if we use a bitvector 1 instead:

```
(define-symbolic b (bitvector 1))
(define valid (box b))
(if (not (bitvector->bool (unbox valid)))
      (set-box! valid (bv 1 1))
      (void))
(if (not (bitvector->bool (unbox valid)))
      (set-box! valid (bv 1 1))
      (void))

; Rosette misses the simplification, valid is :
(box
 (ite (bveq (bv #b0 1) (ite (bveq (bv #b0 1) b) (bv #b1 1) b)) (bv #b1 1) (ite (bveq (bv #b0 1) b) (bv #b1 1) b)))
```

Would there be a way to ask/teach Rosette to consider the same simplification that it does on booleans, when working with bitvector 1?

**Comment by emina** [comment]
Rosette handles bitvectors uniformly, and doesn't perform any rewrites based on the size of the bitvector domain.  It would be possible to extend the rewrite rules to special-case some bitvector lengths, such as 1, but this is generally not worth the overhead.  To a first approximation, adding a rewrite rule adds overhead to all Rosette programs, so Rosette tries to include only rules that are useful for the majority of programs.  (The rules for simplifying booleans are particularly aggressive because of the high value we get from simplifying branching decisions to constants T/F.)

In this case, I would recommend using booleans to represent all values that are known to be bitvectors of length 1, and then converting to bitvectors only when needed.  For example:

```
#lang rosette


(define-symbolic b boolean?)
(define valid (box b))
(if (not (unbox valid))
    (set-box! valid #t)
    (void))
(if (not (unbox valid))
    (set-box! valid #t)
    (void))

(bool->bitvector valid 1)
```
