### ISSUE TITLE
(expression) pattern matching forms not allowing commutativity

### ISSUE THREAD

**Issue by Cazra** [emina/rosette#185]
When using the pattern matching forms for nested expressions that use commutative ops, it fails to match against equivalent expressions where terms have just been moved around.

For example:

`(match P [(expression && a b (expression || c d)) #t] [_ #f])`

might match for P, but 

`(match P [(expression && (expression || d c) b a) #t] [_ #f])`

would not, even though they are logically equivalent, following laws of commutativity. 

Here's a whole code snippet that can reproduce the issue in the Racket REPL:
```
> (require rosette/safe)
> (define-symbolic a boolean?)
> (define-symbolic b boolean?)
> (define-symbolic c boolean?)
> (define-symbolic d boolean?)
> (define P (&& a b (|| c d)))
> (match P [(expression && (expression || d c) b a) #t] [_ #f])
#f
> (match P [(expression && b a (expression || d c)) #t] [_ #f])
#t
> 
```

**Comment by emina** [comment]
Pattern matching won't take into account logical equivalence.  This snippet applies Racket's pattern matching to Rosette's AST for symbolic values, so the pattern must match the syntax of the expression exactly.   

You'd match this expression exactly like this:

```
#lang rosette


(define-symbolic a boolean?)
(define-symbolic b boolean?)
(define-symbolic c boolean?)
(define-symbolic d boolean?)
(define P (&& a b (|| c d)))

(match P
  [(expression (== &&) (== a) (== b) (expression (== ||) (== c) (== d)) ) #t]
  [_ #f])
```

Note also that `match` is not lifted to work on symbolic values.  If you need symbolic evaluation inside of `match` (rather than literal pattern matching), you might want to use `destruct` instead.

**Comment by Cazra** [comment]
I see. So, pattern matching really can't be used to check an expression's structure without knowing exactly how Rosette will arrange it...

Is there another way to check the structure of an expression, like for the use case of unit testing some programmatically-generated expression, which may contain anonymous symbolic constants created with `define-symbolic*`?

**Comment by emina** [comment]
It's not advisable to rely on syntactic structure for testing because this structure is not guaranteed to be stable over different releases.  So any tests that rely on syntax will be flaky.

In this case, the best approach is to verify that the semantics of the generated expression is correct. 

For example:

```
#lang rosette

(define-symbolic a boolean?)
(define-symbolic b boolean?)
(define-symbolic c boolean?)
(define-symbolic d boolean?)

; Generated code
(define P (&& a b (|| c d)))
P

; Expected semantics
(define S (expression && (expression || d c) b a))
S

(verify
 (assert
  (equal? P S)))

; The output is:
(&& a b (|| c d))
(&& (|| d c) b a)
(unsat)
```

Constructing expressions directly, as shown above, should be reserved only for unit testing.

**Comment by Cazra** [comment]
Thanks. I'll try that.
