### ISSUE TITLE
Difference in satisfiability of `verify` between Racket 7.9 and 8.0, uninterpreted functions

### ISSUE THREAD

**Issue by avanhatt** [emina/rosette#190]
Hi! I believe I am getting a difference in satisfiability for equivalent `verify` commands (with differing old vs new syntax) for Racket 7.9 (Rosette 25b0673ade9302f81e9) and Racket 7.0 (Rosette 9f6322c9da5761da631). The verification time with the newer version is also about an order of magnitude slower for a small example (0.5s vs 9s). 

The old version (`verify-uninterp-7.rkt`):
```
#lang rosette

(define-symbolic sgn (~> real? real?))

(define (sgn-implementation v)
  (- (> v 0) (< v 0)))

(define (uninterp-fn-assumptions)
  (define-symbolic a real?)
  (forall (list a) (equal? (sgn a) (sgn-implementation a))))

(verify #:assume (assert (uninterp-fn-assumptions))
        #:guarantee true)
```

The new version (`verify-uninterp-8.rkt`): 
```
#lang rosette

(define-symbolic sgn (~> real? real?))

(define (sgn-implementation v)
  (- (> v 0) (< v 0)))

(define (uninterp-fn-assumptions)
  (define-symbolic a real?)
  (forall (list a) (equal? (sgn a) (sgn-implementation a))))

(verify
 (begin
   (assume (uninterp-fn-assumptions))
   (assert true)))
```

Results:
```
diospyros (master) $ time /Applications/Racket\ v7.9/bin/racket verify-uninterp-7.rkt
(unsat)

real	0m0.490s
user	0m0.371s
sys	0m0.107s
diospyros (master) $ time /Applications/Racket\ v8.0/bin/racket verify-uninterp-8.rkt
(model)

real	0m9.272s
user	0m8.942s
sys	0m0.191s
```

Expected results: (unsat) for both queries, the setup of assuming the value of the `sgn` function should not fail verification. 

Apologies if I'm just holding the new syntax wrong, and thanks!

**Comment by avanhatt** [comment]
Ah it looks like the actual problem is that `sgn-implementation` function is broken; it fails with:
```
[assert] $-: expected real? arguments
  arguments: ((< 0 a))
```

Still not sure why the versions of Rosette differ.

**Comment by emina** [comment]
The 4.0 version returns instantaneously for me with Racket 8.0 and Z3 version 4.8.8 - 64 bit (on an old Mac).

The behavior is different because putting an `assume` expression inside of `verify` is not equivalent to using `#:assume` in the old version.  In particular, `#:assume` captures all errors and assertion failures and treats them as assumptions.  The `assume` expression doesn't do that, so the error in `sgn-implementation` manifests as an assertion failure in Rosette 4.0.  This leads the query to immediately return with a trivial counterexample (the empty model).

(See the docs for the `verify` query and for `assume` for details on the new semantics.)

To make the two queries equivalent, you'd write something like this:

```
#lang rosette

(define-symbolic sgn (~> real? real?))

(define (sgn-implementation v)
  (- (> v 0) (< v 0)))

(define (uninterp-fn-assumptions)
  (define-symbolic a real?)
  (forall (list a) (equal? (sgn a) (sgn-implementation a))))

; Capture any errors and assumptions.
(define c
  (with-vc (assume (uninterp-fn-assumptions))))

; To get Rosette 3 #:assume behavior, use the assertions and
; assumptions in c as assumptions to this query:
(verify
 (begin
   (assume (&& (vc-assumes (result-state c))
               (vc-asserts (result-state c))))
   (assert true)))

```
