### ISSUE TITLE
match behavior is inconsistent between normal and symbolic execution

### ISSUE THREAD

**Issue by whitequark** [emina/rosette#216]
The following example illustrates the inconsistency:

<details>

```racket
#lang rosette/safe
(require rosette/lib/match
         rosette/lib/angelic)

(struct n ()  #:transparent)
(struct s (a) #:transparent)

(define (len e)
 (match e
  [(s v)     (+ 1 (len v))]
  [(n)       0]))

(define (len* e)
 (match e
  [(s (s v)) (+ 2 (len v))]
  [(s v)     (+ 1 (len v))]
  [(n)       0]))

(define-symbolic a boolean?)
(define e1 (n))
(define e2 (s (n)))
(define e3 (s (s (n))))
(define es (list e1 e2 e3))

(displayln (map len es)) ; (0 1 2)
(displayln (len (apply choose* es))) ; (ite xi?$0 0 (ite xi?$1 1 2))

(displayln (map len* es)) ; (0 1 2)
(displayln (len* (apply choose* es))) ; (ite xi?$0 0 2)
```
</details>

I understand that [`match` in Rosette is limited](https://github.com/emina/rosette/issues/134#issuecomment-565893932). But... if it lacked support for nested patterns entirely, it would've been straightforward to narrow down the issue. I didn't, though, expect it to correctly match a nested non-exhaustive pattern and ignore the other possible variants! I've spent many hours questioning every other part of the program (and myself) before I figured this out.

I understand that since the last time I used Rosette, [a `destruct` construct was introduced](https://github.com/emina/rosette/pull/172) that doesn't have these issues (and prints a very nice error message when trying to match on a nested pattern). Still, I think it would be valuable to avoid silent miscompilations in `match`.

**Comment by emina** [comment]
Yes, `match` is tricky to use, and we recommend using `destruct` instead when your program needs safe / lifted symbolic evaluation.

There are some legitimate uses for unlifted / partially lifted constructs (such as `match` and hash maps), so we’ve left them in the language as they are.

To help debug unexpected behaviors in Rosette programs (minus `match`), @sorawee has developed a new tool called the Error Tracer:  https://docs.racket-lang.org/rosette-guide/ch_error-tracing.html

We’ve found the tool valuable for localizing some common errors that are due to the use of unsafe code.  While it doesn’t play nice with `match`, it might have helped rule out other parts of the code more quickly.  

We hope you give it a try in the future!

**Comment by whitequark** [comment]
> @sorawee has developed a new tool called the Error Tracer: https://docs.racket-lang.org/rosette-guide/ch_error-tracing.html

I've noticed the appearance of this tool! I've tried using it to debug the `match` issue, but, like you've mentioned, it didn't help there. I'll keep it in mind for other issues!

Please feel free to handle this issue as you wish--I just wanted to record the unsoundness here, which I think isn't currently something that one could reasonably expect.

**Comment by emina** [comment]
> Please feel free to handle this issue as you wish--I just wanted to record the unsoundness here, which I think isn't currently something that one could reasonably expect.

Yes, thank you; good to have a record in case others run into the same issue!

I’m glad you found and tried the error tracer, and yes, there is a good chance it will be more helpful in the future :)
