### ISSUE TITLE
Strange behavior with choose while synthesizing

### ISSUE THREAD

**Issue by ManuelEberhardinger** [emina/rosette#227]
Hello, I am playing a bit with Rosette as I am thinking to use it in my research. I did the tutorial and tried out some basic stuff to understand how Racket and Rosette are working. This is my code right now which is working (I tried to strip everything out to make the example clear):

```
#lang rosette/safe
(require rosette/lib/synthax rosette/lib/angelic)

(define-grammar (plans-dsl a_h)
  [s (choose (append a_h (list (choose 4 5 6 7))))]
)

(define previous_actions (list 0 1 2 3))

(define (test-loop)
    (let loop ((aux1 previous_actions) (len (choose 0 1)))
        (if (> len 0)
            (loop (plans-dsl aux1 #:depth 2) (- len 1))
          (plans-dsl aux1 #:depth 2)))
  )

(define (sol val)
    (synthesize
     #:forall (list)
     #:guarantee (assert (equal? (test-loop) val))))
```

This produces this output:
```
> (print-forms (sol (list 0 1 2 3 5 6)))
                    
(define (test-loop)
  (let loop ((aux1 previous_actions) (len 1))
    (if (> len 0)
      (loop (choose (append aux1 (list 5))) (- len 1))
      (choose (append aux1 (list 6))))))

; this produces an unsat which is also correct
>  (print-forms (sol (list 0 1 2 3 5 5 6)))
. . sat-model: contract violation
  expected: sat?
  given: (unsat)
```

This also finds the solution instantly, but if I change the test-loop to choose from three different values or use the ?? operator, the query runs until I get a memory exception. 

This is not working:
```
(define (test-loop)
    (let loop ((aux1 previous_actions) (len (choose 0 1 2)))
        (if (> len 0)
            (loop (plans-dsl aux1 #:depth 2) (- len 1))
          (plans-dsl aux1 #:depth 2)))
  )

(print-forms (sol (list 0 1 2 3 5 6)))
; Output: The evaluation thread is no longer running, so no evaluation can take place until the next execution. The program ran out of memory.
```
I already increased the memory to 2048MB but I don't think that this is the issue as choose with 2 values and 256MB was working.
This is also not working:
```
(define (test-loop)
    (let loop ((aux1 previous_actions) (len (?? integer?))
        (if (> len 0)
            (loop (plans-dsl aux1 #:depth 2) (- len 1))
          (plans-dsl aux1 #:depth 2)))
  )

(print-forms (sol (list 0 1 2 3 5 6)))
; the same memory exception as before
```
Am I using Rosette the wrong way? I don't understand why choose is working without problems with 2 values but with 3 values I get a memory exception.

Thanks in advance!

**Comment by ManuelEberhardinger** [comment]
Oh thank you very much for the slides! Now it is working as expected :)

**Comment by ManuelEberhardinger** [comment]
Sorry for bothering you again, but I would have another question and I somehow think that this is connected to the previous behaviour of choose.

I have this code which is working:

```
#lang rosette/safe
(require rosette/lib/synthax)
(current-grammar-depth 4)

(define-grammar (Action previous_actions)
  [act (append previous_actions (list (choose 0 1 2 3 4)))])

(define-grammar (Action_Block previous_actions)
  [act (choose previous_actions (Action previous_actions) (Action (Action previous_actions)))])

(define-grammar (Block previous_actions perceptions)
  [cond (Action_Block previous_actions)])

(define prog
  (Block (list) (list) #:depth 5))

(define sol
  (synthesize
   #:forall (list )
   #:guarantee (assert (equal? prog (list 0 4)))))
(print-forms sol)
````
This outputs the correct completed function: `(define prog (append (append (list) (list 0)) (list 4)))`

When I change the Action_Block to:
````
(define-grammar (Action_Block previous_actions)
  [act (choose previous_actions (Action previous_actions) (Action (act)))])
`````
for a grammar depth of 2 I get unsat and for grammar depth of 4 it is somehow running until I get an exception. 

I wanted to have a dynamic expansion of the Action which could be done in Rosette 3 with this block:
````
(define-synthax (Action_Block previous_actions length)
  #:base previous_actions
  #:else (choose
          previous_actions
          (let ([new_actions (Action_Block previous_actions (- length 1))])
            (Action new_actions))))
````
I thought that the `current-grammar-depth` would restrict the expansion similar to the length parameter in the `define-synthax` function above. I already tried to use the error tracer (https://docs.racket-lang.org/rosette-guide/ch_error-tracing.html) but this is the only output of the error tracer:

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/14148740/161385557-19dc7cf1-3139-4e25-b0dc-dc36657d603a.png">

I don't find any tutorials or articles to get a deeper understanding of Rosette except the official documentation. Do you have some helpful resources? 

Thanks in advance!

**Comment by sorawee** [comment]
Renaming one of the `act`s to `act2` seems to do the trick. That is, it appears that there can't be two rule-ids with the same name, even across `define-grammar`. This is surprising to me, and unless I miss anything, I think this might be considered a bug. ( @emina can confirm :) )

By the way, you could also write the following:

```
(define-grammar (Action_Block previous_actions)
  [act (choose previous_actions (Action (act)))])
```

There is no need for `(Action previous_actions)` since it's already covered by `(Action (act))`.

**Comment by emina** [comment]
This is due to a bug in the code generation algorithm implemented in `generate-forms`.  

If you add `(println "DONE solving")` right before the call to `print-forms`, you'll see that Rosette successfully generates the formula for depth 4 and Z3 solves it.  

After this point, the generator goes into an infinite loop trying to expand `act` because it can't distinguish between the two uses of the same symbol.  This is why renaming one of them solves the issue.

I'll see if there is a way to fix this.

In the meantime, I strongly recommend solving your synthesis problem via a deep embedding.  It does require more upfront investment than a shallow embedding, but it will also give you more flexibility and control over the synthesis process. 

As a general rule of thumb, if you're doing synthesis, deep embedding is the way to go :)

For an example, see [this blog post](https://www.cs.utexas.edu/~bornholt/post/building-synthesizer.html) from @jamesbornholt.

**Comment by ManuelEberhardinger** [comment]
Thanks for the explanation and tips! I will have a look at the blog post for the deep embeddings, as I want to use Rosette for synthesis problems :)
