### ISSUE TITLE
nested `ite` in `bvshl` does not get reduced

### ISSUE THREAD

**Issue by stchang** [emina/rosette#23]
Evaluating:
```racket
(bvand (bv -1 4) (if b (bv 3 4) (bv 2 4)))
```
where `b` is `(define-symbolic b boolean?)`, produces:
```racket
(ite b49 (bv 3 4) (bv 2 4))
```

But evaluating:
```racket
(bvshl (bv -1 4) (if b (bv 3 4) (bv 2 4)))
```
produces:
```racket
(bvshl (bv -1 4) (ite b49 (bv 3 4) (bv 2 4)))
```

Is this the intended behavior, or should the `bvshl` operation be pushed into the `ite` branches, as with `bvand`?

**Comment by emina** [comment]
This simplification could be implemented by bvshl as well.  It's not a bug in the sense that it doesn't affect correctness.  It's implemented for bvand etc. since those are the cases that we have seen occur most often in practice.  Which simplifications to implement is essentially a tradeoff between performance of symbolic evaluation and the underlying solver.

**Comment by stchang** [comment]
Thanks for the explanation.
