### ISSUE TITLE
Question: Lifted forms

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#77]
Hello,

I can see `let` is lifted but `for` is not. However, there's no mention if the special `let <label>` form is lifted that allows recursion. Is it?

What is in general the best way to determine if a specific form is lifted? Is there some test I can run to see if lifting is occurring?

**Comment by emina** [comment]
The `let <label>` form is lifted as well.  Note, however, that the programmer is responsible for ensuring that any recursion involving symbolic termination conditions does, in fact, terminate. This is also true for recursive functions implemented with `define`.  Essentially, just like Racket requires the programmer to ensure that normal recursive procedures terminate, Rosette does as well, in the presence of both symbolic and concrete values.

For example, the following program will run forever because of the symbolic termination condition:

```
#lang rosette

(define (fib n)
  (if (<= 0 n 1)
      n
      (+ (fib (- n 1))
         (fib (- n 2)))))

(define-symbolic* n integer?)

> (map fib '(0 1 2 3 4 5 6 7 8 9 10))
'(0 1 1 2 3 5 8 13 21 34 55)
 
> (solve (assert (> (fib n) 20))) ; runs forever 
```

If you want Rosette to only consider executions of bounded length, then this has to be specified explicitly:

```
(define (fib-k n [k 5]) ; k is the recursion bound, with a default of 5
  (if (> k 0)
      (if (<= 0 n 1)
          n
          (+ (fib-k (- n 1) (- k 1))
             (fib-k (- n 2) (- k 1))))
      (assert #f)))

(current-bitwidth 8)
(define-symbolic* n integer?)

; This gives unsat because the bound is not high enough ...
> (solve (assert (> (fib-k n) 20)))
(unsat)

; This works because there is an n that satisfies the assertion within k = 10 steps.
> (solve (assert (> (fib-k n 10) 20)))
(model
 [n$0 9])
```

(It's possible to write a `define/bounded` macro that will insert the bounding code by default, so that the application code doesn't have to include it.)

In general, you can see which forms are lifted by Rosette by typing

```
> (rosette)
'(solver-assert
  solver-check
  solver-clear ...)
```
