### ISSUE TITLE
Omission: values in lifted forms

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#78]
In the lifted forms documentation [1] there is a reference to lifted value `let-values` and `define-values` but no reference to `values`. It seems this is an omission. It doesn't seem to make sense to lift `let-values` and `define-values` which are values consumers but not `values`, the values producer.

Am I correct into thinking, therefore that `values` is also lifted but not documented?

1. http://docs.racket-lang.org/rosette-guide/ch_syntactic-forms_racket.html?q=rosette

**Comment by emina** [comment]
The `values` form is not lifted because Rosette doesn't support multiple return values.  Specifically, by not lifting `values` or other forms that may return multiple values, the `rosette/safe` fragment makes it impossible to write a program that will return more than one value. Such programs can be written in `rosette` but may result in crashes or other unexpected behaviors.

For example, this will crash:

```
#lang rosette

(define-symbolic* b boolean?)
(if b
    (values 1 2)
    (values 3 4))
```

But this will work because multiple return values aren't guarded by symbolic conditions:

```
#lang rosette

(define b #t)
(if b
    (values 1 2)
    (values 3 4))
```

`define-values` and `let-values` are lifted in `rosette/safe` because they can be used with single values:

```
> (define-values (x) 1)
> x
1
```
