### ISSUE TITLE
Cond missing support for =>

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#83]
As far as I understand it rosette supports `cond` with no exceptions (at least, they are not mentioned in the docs).

However this does not work:
```racket
#lang rosette
(define v 3)

(cond [v => identity]
      [else 2])
```
This returns `#<procedure:identity>`. In `#lang racket` returns, as it should `3`.

**Comment by emina** [comment]
This is correct behavior under the Rosette semantics, since the identifier [=>](https://emina.github.io/rosette/rosette-guide/sec_bools_ints_reals.html#%28def._%28%28lib._rosette%2Fbase%2Fbase..rkt%29._~3d~3e%29%29) is bound to a procedure that implements logical implication.  To see that, consider the following examples:

```
#lang rosette

(define v 3)
(define p =>)

(cond [v p identity]
      [else 2]) ;  returns identity

(cond [v + identity]
      [else 2]) ; returns identity

```

Since `=>` has special meaning in Rosette, `cond` clauses of the form `[test-expr => proc-expr]` aren't supported.
