### ISSUE TITLE
bug with using 'member' in assertions?

### ISSUE THREAD

**Issue by alanborning** [emina/rosette#9]
I've got some Wallingford code that works using this function:

(define (button-pressed)
  (if (member symbolic-time button-down-event-times) #t #f))

but not the clean version:

(define (button-pressed)
  (member symbolic-time button-down-event-times))

Is this a bug? I distilled out some code to exhibit this, which is in reactive/bug.rkt in the Wallingford repository at https://github.com/alanborning/wallingford.git

If you run the code in the repository it prints out:
button is pressed at time 3 
button is pressed at time 8 
button is pressed at time 10 
advanced time to 100 

If you change the button-pressed function it doesn't catch the button pressed events.

**Comment by jamesbornholt** [comment]
This is because these two versions aren't quite the same: `(member ...)` returns the tail of the list or `#f`. While lists behave as `#t` for the purposes of `if`, in this code we're asserting that the return of `(member ...)` is equal to a boolean variable `one-when-condition-holds`. Rosette notices that lists and booleans can never be equal in Racket, and so simplifies that assertion to one that asserts the return value of the `(member ...)` call is `#f`.
