### ISSUE TITLE
unix 32 support

### ISSUE THREAD

**Issue by pmatos** [emina/rosette#94]
I am trying rosette on a (yes!) rpi. :) This is an arm based cpu with no issues running racket, rosette or z3, however it turns out that there's no entry on `private/install.rkt` so it can't automatically install z3. 

I see you have purpose-built z3 on the releases folder which you download. How can one add a build for `(unix 32)`?

**Comment by jamesbornholt** [comment]
`install.rkt` currently assumes x86, so adding a case for `(unix 32)` probably won't do what you want on a rpi (which is ARM). I'm not too sure we want to get into distributing ARM builds, since the official z3 repo doesn't do that, and ARM is pretty diverse. But maybe we should add better error messaging if the case detection fails in `install.rkt` to tell you what to do (go get your own build of z3).

**Comment by emina** [comment]
Yes, we will provide a better error message for this, as suggested by @jamesbornholt.

@pmatos, given that z3 doesn't support ARM, it seems best to leave it out of the generic distribution of Rosette.

If you can get both Rosette and z3 running individually on ARM, it sounds as though putting the right [z3 binary in `rosette/bin`](https://github.com/emina/rosette/blob/8fa04ccfc939af9869abd1e98c3bbedac7fef207/rosette/solver/smt/z3.rkt#L15) after installation works for you?  If so, a passable solution could be to automate that last step with a custom script in your copy of Rosette.

**Comment by pmatos** [comment]
@emina Understood. I will, in the meantime, sort myself out with an ARM self-build z3. It seems to work. Thanks for your comments.

**Comment by emina** [comment]
👍
